### ISSUE TITLE
Highlighting Stars

### ISSUE THREAD

**Issue by lwthatcher** [nOkuda/activetm#3]
When hovering over the stars the cursor should change to be a pointer, rather than staying as the default cursor. This would help make the affordance more clear.

**Comment by nOkuda** [comment]
What is the difference between a cursor and a pointer?   Could you provide an example?

**Comment by lwthatcher** [comment]
Sorry, when I said pointer I was referring to the little finger icon such as when you click a link.
 **(similar to: :point_up_2: )**

This can easily be done using css:

> div {
>     cursor:pointer;
> }

Just replace `div` with the selector for the stars element.

**Comment by nOkuda** [comment]
Done.
