### ISSUE TITLE
The accuracy used to track labeling performance fails to capture labeling quality

### ISSUE THREAD

**Issue by jefflund** [nOkuda/activetm#4]
If I label a 5 star rating with a 1, then I am doing worse than labeling the same 5 star rating with a 4. However, simply tracking a binary correct/incorrect labeling fails to capture this. Please report something like mean squared error or mean absolute error instead.

**Comment by lwthatcher** [comment]
You could do both?

**Comment by nOkuda** [comment]
The code for this issue has been moved to https://github.com/nOkuda/reviewlabeljob.  The code now reports mean absolute error.
